# Generated by Django 5.1.2 on 2024-11-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_testresult_answerselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
