# Generated by Django 5.1.2 on 2024-11-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_testresult_score_testresult_total_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='score',
            field=models.CharField(max_length=40),
        ),
    ]
